name: Build and Push Docker Images (Repository Secrets)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug secrets availability
      run: |
        echo "Checking if repository secrets are available..."
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "ERROR: DOCKER_USERNAME repository secret is not set"
          echo "Please add DOCKER_USERNAME to Repository Settings > Secrets and variables > Actions"
          exit 1
        else
          echo "✅ DOCKER_USERNAME repository secret is available"
        fi
        
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "ERROR: DOCKER_PASSWORD repository secret is not set"  
          echo "Please add DOCKER_PASSWORD to Repository Settings > Secrets and variables > Actions"
          exit 1
        else
          echo "✅ DOCKER_PASSWORD repository secret is available"
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push server Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/cbg-server:latest
          ${{ secrets.DOCKER_USERNAME }}/cbg-server:${{ github.sha }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push client Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/cbg-client:latest
          ${{ secrets.DOCKER_USERNAME }}/cbg-client:${{ github.sha }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max